import type { Metadata } from "next";
import { League_Spartan } from "next/font/google";
import "./globals.css";
import Header from "./components/Header/Header";
import { Providers } from "@/features/provider";
import Footer from "./components/Footer/Footer";

const spartan = League_Spartan({ subsets: ["latin"], weight: ["500", "700"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Providers>
        <body
          className={`${spartan.className} md:flex md:items-center md:flex-col`}
        >
          <Header />
          {children}
          <Footer />
        </body>
      </Providers>
    </html>
  );
}
